[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[invariant]
runs = 1000
depth = 128
fail_on_revert = true


remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
"@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
